spring:
  data:
    mongodb:
      uri: mongodb+srv://flicko:mongoDB123@cluster0.dxoztpb.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  application:
    name: journalApp